### ISSUE TITLE
File browser does not showing the selected file

### ISSUE THREAD

**Issue by beatlejuan5** [creativetimofficial/ct-argon-dashboard-pro-angular#1]
### Version
Current version and demo in the website.
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-angular/#/forms/elements
### Operating System
Windows 10
### Device
PC
### Browser & Version
Google Chrome
### Steps to reproduce
Select a file in the file browser input.
### What is expected?
Must works like the imagepicker from other dashboards like paper and material, here must to show the name of the file selected.
### What is actually happening?
I select a file but the file browser input does not show the name of the file selected.

---
### Solution
I think the css or some dependency are not working.
### Additional comments
This dashboard needs to implements file browser and imagepicker like paper, material and other dashboards.

**Comment by beatlejuan5** [comment]
Hi, I need to homologate a argon web app with Material Dashboard and Paper Dashboard, I need to make a image picker and a input file picker, with the image picker from the others dashboard I make a file picker easily, but with argon I don't have the way. @chelaruc

**Comment by chelaruc** [comment]
Hi, @beatlejuan5. Thank you for using our product. This file input is the default file input and we haven't done it to work. You can use the dropzone from [https://demos.creative-tim.com/argon-dashboard-pro-angular/#/forms/components](https://demos.creative-tim.com/argon-dashboard-pro-angular/#/forms/components). All the best, Ciprian

**Comment by beatlejuan5** [comment]
Hi @chelaruc Can you tell me the steps to adapt Jasny Bootstrap to this template like you did it with paper and materia angularl versions. Regards

**Comment by chelaruc** [comment]
@beatlejuan5 to use Jasny Bootstrap you need jQuery and that is not a good mode to build your Angular projects.

**Comment by beatlejuan5** [comment]
@chelaruc But Material and Paper Dashboard use it, or there are plans of remplace it and add it to argon dashboard?

**Comment by beatlejuan5** [comment]
@chelaruc
