### ISSUE TITLE
[Bug] Unable to run the application (ng serve)

### ISSUE THREAD

**Issue by perseghini** [creativetimofficial/ct-argon-dashboard-pro-angular#13]
### Version
latest (1.2.0)
### Reproduction link
https://jsbin.com/
### Operating System
Mac OS 10.15.7
### Device
MacBook Pro
### Browser & Version
Chrome (latest)
### Steps to reproduce
npm install
ng serve
### What is expected?
The application should compile and run
### What is actually happening?
ERROR in ./node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js 4283:12-27
"export 'ɵisSubscribable' was not found in '@angular/core'

---
### Solution
It seems "Argon Dashboard Pro Angular" was not completely migrated to Angular11. Some packages are still using an old incompatible version (ie: @angular/http:7.2.16 ).
You can also try to run "ng update @angular/cli", "ng update @angular/core" and "rxjs" to see some current issues with the migration to Angular 11.

I tried to manually update the old packages but then ran into this issue:
"FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory"

**Comment by rarestoma** [comment]
Hi @perseghini,

Thank you for working with our products.

We tried updating but we also receive this fatal error. We will still try to fix it and we will come with updates.

Thank you,
Rares

**Comment by fb2062** [comment]
Same issue...

**Comment by rarestoma** [comment]
Hi @fb2062,

Thank you for working with our products.

Can you please tell me what error do you get?

Thank you,
Rares

**Comment by fb2062** [comment]
Hi Rares,

As summary;

Version
latest (1.2.0)

Operating System
Mac OS 10.15.7

Device
MacBook Pro

Browser & Version
Chrome (latest)

Steps to reproduce
npm install
ng serve

What I get?
ERROR in ./node_modules/@angular/common/ivy_ngcc/fesm2015/common.js 4283:12-27
"export 'ɵisSubscribable' was not found in '@angular/core'

Fatih.

**Comment by rarestoma** [comment]
Hi @fb2062,

Please replace in package.json  `"@angular/common": "^11.0.5"` with   `"@angular/common": "11.0.5"`, delete node_modules and package.lock.json and install the project.

Please let me know if it works.

Thank you,
Rares

**Comment by fb2062** [comment]
Hi Rares, 

It worked.
Thank you for support.

Fatih.

**Comment by perseghini** [comment]
Hey @rarestoma,

This fixed the issue,
You're the best!

**Comment by aghwotu** [comment]
> Hi @fb2062,
> 
> Please replace in package.json `"@angular/common": "^11.0.5"` with `"@angular/common": "11.0.5"`, delete node_modules and package.lock.json and install the project.
> 
> Please let me know if it works.
> 
> Thank you,
> Rares

Can this solution be added to the README? Maybe as a 'Gotcha' suggestion in the event, a user encounters this error? My company bought this theme today and this would have saved us some time if it was included in the README. 

Thank you for building this theme.
