### ISSUE TITLE
[Bug] Unable to add a dropdown inside the ngx-table

### ISSUE THREAD

**Issue by aghwotu** [creativetimofficial/ct-argon-dashboard-pro-angular#26]
### Version
1.2.0
### Reproduction link
https://jsfiddle.net/ediri/dnc7tqj9/
### Operating System
macO
### Device
macOS BigSur
### Browser & Version
Google Chrome Version 96.0.4664.110
### Steps to reproduce
1. Add the dropdown from the Sortable table inside a column in the Ngx Datatable
### What is expected?
A dropdown just like the one seen in the Sortable table
### What is actually happening?
It is not displayed and further edits render it unusable. Please help. A demo showing a dropdown in the ngx-table would be helpful to future users. 

---

**Comment by rarestoma** [comment]
Hi @aghwotu,

Thank you for working with our products.

Can you please give me the code that you used so I can test it and see how can we fix this issue?

Thank you,
Rares
