### ISSUE TITLE
Bootstrap Modals keep adding padding-right to body every after closed

### ISSUE THREAD

**Issue by mpanjiz** [creativetimofficial/ct-argon-dashboard-pro-angular#29]
when i open modal BsModalRef, bootstrap modals keep adding padding-right 19px to body after closed, and always increasing every i open and close modal. Is there a solution to overcome this? Thank you
![padding right](https://user-images.githubusercontent.com/80385109/150416577-4022bc3f-3071-424e-8e24-54f7f517157b.JPG)

**Comment by bkhalifa** [comment]
you shoud add 
	<style>
		body {
			padding-right: 0px !important;
			overflow: auto !important;
		}
	</style>
in the index.html
