### ISSUE TITLE
[Bug] [BUG] Bootstrap Modals keep adding padding-right to body after closed

### ISSUE THREAD

**Issue by mpanjiz** [creativetimofficial/ct-argon-dashboard-pro-angular#32]
### Version
1.2.0
### Reproduction link
https://github.com
### Operating System
Windows 10
### Device
Hp
### Browser & Version
Chrome
### Steps to reproduce
Add modal BsModalRef
open modal
close modal
### What is expected?
the dashboard screen remains in full view even though you have opened or closed the modal
### What is actually happening?
the dashboard screen gets smaller every time I close the modal that I open. when inspected, there is an addition of padding-right 19 every time I open and close the modal, and it keeps growing. I just got back to how it was when I reloaded. Please help

---

**Comment by rarestoma** [comment]
Hi @mpanjiz,

Thank you for working with our products.

Can you please give me a video with your issue so I can see exactly what happens?

Thank you,
Rares
